#######################################################
# This workflow gets triggered when a push to the
# main branch occurs (eg pull request from develop). 
# It performs the following tasks:
#
#    - log the git branch/commit details
#    - install Go v1.15
#    - run go vet/lint
#    - install CodeQL
#    - compile the code
#    - run CodeQL analysis
#    - tar the compiled binary
#    - run any go test cases
#    - upload the tar file as a workflow artefact
#
#######################################################

name: Perform build
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Variables for the build job
    env:
      config: 'Release'
      out-dir: '${{ github.workspace }}/out'
      src-dir: '${{ github.workspace }}/src'
    
    # Build steps
    steps:
    - uses: actions/checkout@v2
    
    # Log basic info
    - name: Log git event info
      run: |
        echo Event: ${{ github.event_name }}
        echo Git Ref: ${{ github.ref }}
        echo Git SHA: ${{ github.sha }}
    
    # Setup DotNet Core
    - name: Setup DotNet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101'
    
    # Install all the dependencies
    - name: Install dependencies
      run: |
        dotnet restore

    # Setup CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: csharp

    # Run DotNet build 
    - name: Perform build
      run: |
        dotnet build --configuration ${{ env.config }} --no-restore ${{ env.src-dir }} -o ${{ env.out-dir }}
        ls -al ${{ env.out-dir }}
        
    # Run CodeQL analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
