#######################################################
# This workflow gets triggered when a push to the
# main branch occurs (eg pull request from develop). 
# It performs the following tasks:
#
#    - log the git branch/commit details
#    - install DotNet Core v3.1
#    - install dependencies
#    - initialize CodeQL
#    - compile the code
#    - run CodeQL analysis
#
#######################################################

name: Perform build & test
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Variables for the build job
    env:
      config: 'Release'
      dir-build: '${{ github.workspace }}/build'
      dir-src-project: '${{ github.workspace }}/selfservicebot/src/'
      dir-test-project: '${{ github.workspace }}/selfservicebot/test'
      file-src-project: 'SelfServiceBot.csproj'
      file-test-project: 'SelfServiceBot.Tests.csproj'
    
    # Build steps
    steps:
    - name: Setup Git Checkout
      uses: actions/checkout@v2
    
    # Log basic info
    - name: Log Info
      run: |
        echo Event: ${{ github.event_name }}
        echo Git Ref: ${{ github.ref }}
        echo Git SHA: ${{ github.sha }}
        ls -al ${{ env.dir-src-project }}
        ls -al ${{ env.dir-test-project }}
    
    # Setup DotNet Core
    - name: Setup DotNet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101'
    
    # Install all the dependencies
    - name: Install dependencies
      run: |
        dotnet restore '${{ env.dir-src-project }}/${{ env.file-src-project }}'

    # Initialize CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: csharp

    # Run DotNet build 
    - name: Perform build
      run: |
        dotnet build --configuration ${{ env.config }} --no-restore '${{ env.dir-src-project }}/${{ env.file-src-project }}' -o ${{ env.dir-build }}
        ls -al ${{ env.build-dir }}
        
    # Run CodeQL analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
