#######################################################
# This workflow gets triggered when a push to the
# main branch occurs (eg pull request from develop). 
# It performs the following tasks:
#
#    - log the git branch/commit details
#    - install Python v3.8
#    - initialize CodeQL
#    - run CodeQL analysis
#    - install dependencies
#    - perform tests
#    - upload the source as an artefact
#
#######################################################

name: Perform build & test
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Variables for the build job
    env:
      dir-src: '${{ github.workspace }}/selfservicebot'
      dir-tests: '${{ github.workspace }}/selfservicebot/tests'
      file-requirements: '${{ github.workspace }}/requirements.txt'
    
    # Build steps
    steps:
    
    # Setup git checkout
    - name: Setup Git Checkout
      uses: actions/checkout@v2
    
    # Log basic info
    - name: Log Info
      run: |
        echo Event: ${{ github.event_name }}
        echo Git Ref: ${{ github.ref }}
        echo Git SHA: ${{ github.sha }}
        echo Source Directory: 
        ls -al ${{ env.dir-src }}
    
    # Setup Python
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    # Initialize CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: python
        setup-python-dependencies: false
        config-file: ./.github/codeql/codeql-config.yml

    # Run CodeQL analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
    
    # Install the dependencies
    - name: Install dependencies
      run: |
        pip3 install --target=${{ env.dir-src }} -r ${{ env.file-requirements }}
        echo Source Directory: 
        ls -al ${{ env.dir-src }}
        echo "CODEQL_PYTHON=$(which python)" >> $GITHUB_ENV
        echo CODEQL_PYTHON: $CODEQL_PYTHON
    
    # Run the tests
    # TODO!!!
    
    # Upload artefact
    - name: Upload artefact
      uses: actions/upload-artifact@v2
      with:
        name: SelfServiceBot
        path: |
          ${{ env.dir-src }}
          !${{ env.dir-tests }}

